apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-test-chart-nginx-deployment
  namespace: spinnaker-test-chart
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
            - name: spinnaker-test-chart-configmap-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: spinnaker-test-chart-configmap-volume
          configMap:
            name: spinnaker-test-chart-configmap
